version: '3.8'

services:
  biddingservice:
    image: rasmusdd/biddingservice-image:1.0.0
    container_name: biddingservice
    hostname: biddingservice
    ports:
      - "83:8080"
    environment:
      - ConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=Bidding
    networks:
      - auctionnetwork
      
  auction-service:
    image: jakobhaulund/auction-service-image:latest
    ports:
      - 84:8081
    container_name: auction-service
    hostname: auction-service
    networks:
      - auctionnetwork
      
 # authenticationservice:
  #  image: rasmusdd/authenticationservice-image:latest
   # ports:
    #  - 82:8080
    #environment:
     # - ConnectionString=mongodb://admin:1234@mongodb:27017
      #- DatabaseName=4SemProj
      #- collectionName=Bruger
      #- vaultConnectionString=https://vault_dev:8201
    #container_name: authenticationservice
    #hostname: authenticationservice
    #networks:
     # - auctionnetwork
    #command: ["/bin/sh", "-c", "sleep 20 && dotnet Authentication.dll"]

  userservice:
    image: jakobhaulund/bruger-service-image:latest
    ports:
      - 80:8082
    environment:
      - ConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=Bruger
    container_name: userservice
    hostname: userservice
    networks:
      - auctionnetwork
      
  catalogservice:
    image: rasmusdd/catalogservicegit-image:latest
    container_name: catalogservice
    hostname: catalogservice
    ports:
      - 81:8083
    environment:
      - ConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=Katalog
    networks:
      - auctionnetwork
      
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - catalogservice
      - userservice
      - auction-service
      - biddingservice
    ports:
      - "85:8086"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - auctionnetwork
  
networks:
  auctionnetwork:
    driver: bridge
    external: true
