version: '3.8'

services:
  biddingservice:
    image: rasmusdd/biddingservice-image:1.0.0
    container_name: biddingservice
    hostname: biddingservice
    ports:
      - "83:8080"
    environment:
      - vaultConnectionString=https://vaulthost:8201
      - QueueHostName=rabbitmq
    networks:
      - auctionnetwork
    restart: unless-stopped

      
  auction-service:
    image: jakobhaulund/auction-service-image:latest
    ports:
      - 84:8080
    environment:
      - DatabaseName=4SemProj
      - collectionName=Auction
      - QueueHostName=rabbitmq
      - vaultConnectionString=https://vaulthost:8201
    container_name: auction-service
    hostname: auction-service
    networks:
      - auctionnetwork
    restart: unless-stopped

  userservice:
    image: jakobhaulund/bruger-service-image:latest
    ports:
      - 80:8080
    environment:
      - DatabaseName=4SemProj
      - collectionName=User
      - vaultConnectionString=https://vaulthost:8201
    container_name: userservice
    hostname: userservice
    networks:
      - auctionnetwork
    restart: unless-stopped

  catalogservice:
    image: rasmusdd/catalogservicegit-image:latest
    ports:
      - 81:8080 
    environment:
      - vaultConnectionString=https://vaulthost:8201
      - DatabaseName=4SemProj
      - collectionName=Catalog
    container_name: catalogservice
    hostname: catalogservice
    networks:
      - auctionnetwork
    restart: unless-stopped

  authenticationservice:
    image: rasmusdd/authenticationservice-image:latest
    ports:
      - 82:8080
    environment:
      - vaultConnectionString=https://vaulthost:8201
      - userservicehost=http://userservice:8080
    container_name: authenticationservice
    hostname: authenticationservice
    networks:
      - auctionnetwork
    command: ["/bin/sh", "-c", "sleep 20 && dotnet Authentication.dll"]
    restart: unless-stopped
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "85:8080"
    depends_on:
      - userservice
      - authenticationservice
      - auction-service
      - biddingservice
      - catalogservice
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - auctionnetwork
  
networks:
  auctionnetwork:
    driver: bridge
    external: true
