version: '3.8'

services:
  biddingservice:
    image: rasmusdd/biddingservice-image:1.0.0
    container_name: biddingservice
    hostname: biddingservice
    ports:
      - "83:8080"
    environment:
      - ConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=Bidding
    networks:
      - auctionnetwork
      
  auction-service:
    image: jakobhaulund/auction-service-image:latest
    ports:
      - 84:8080
    container_name: auction-service
    hostname: auction-service
    networks:
      - auctionnetwork

networks:
  auctionnetwork:
    driver: bridge
    external: true