version: '3.8'

services:
  auction-service:
    image: jakobhaulund/auction-service-image:latest
    ports:
      - 84:8080
    container_name: auction-service
    hostname: auction-service
    networks:
      - auctionnetwork
  
networks:
  auctionnetwork:
    driver: bridge
    external: true