version: '3.8'

services:
  biddingservice:
    image: rasmusdd/biddingservice-image:1.0.0
    container_name: biddingservice
    hostname: biddingservice
    ports:
      - "83:8080"
    environment:
      - vaultConnectionString=https://vaulthost:8201
      - DatabaseName=4SemProj
      - collectionName=Bidding
      - QueueHostName=rabbitmq
      - vaultConnectionString=https://vaulthost:8201
    networks:
      - auctionnetwork
    restart: unless-stopped

      
  auction-service:
    image: jakobhaulund/auction-service-image:latest
    ports:
      - 84:8080
    environment:
      - ConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=Auktion
      - QueueHostName=rabbitmq
      - vaultConnectionString=https://vaulthost:8201
    container_name: auction-service
    hostname: auction-service
    networks:
      - auctionnetwork
    restart: unless-stopped
      
 # authenticationservice:
  #  image: rasmusdd/authenticationservice-image:latest
   # ports:
    #  - 82:8080
    #environment:
     # - ConnectionString=mongodb://admin:1234@mongodb:27017
     # - DatabaseName=4SemProj
     # - collectionName=Bruger
     # - vaultConnectionString=https://vault_dev:8201
    #container_name: authenticationservice
    #hostname: authenticationservice
    #networks:
     # - auctionnetwork
    #command: ["/bin/sh", "-c", "sleep 20 && dotnet Authentication.dll"]

  userservice:
    image: jakobhaulund/bruger-service-image:latest
    ports:
      - 80:8080
    environment:
      - ConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=Bruger
      - vaultConnectionString=https://vaulthost:8201

    container_name: userservice
    hostname: userservice
    networks:
      - auctionnetwork
    restart: unless-stopped

      
  catalogservice:
    image: rasmusdd/catalogservicegit-image:latest
    container_name: catalogservice
    hostname: catalogservice
    ports:
      - 81:8080
    environment:
      - ConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=Katalog
    networks:
      - auctionnetwork
    restart: unless-stopped



  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - userservice
    #  - authenticationservice
      - auction-service
      - biddingservice
      - catalogservice
    networks:
      - auctionnetwork
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "85:8080"
    depends_on:
      - userservice
    #  - authenticationservice
      - auction-service
      - biddingservice
      - catalogservice
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - auctionnetwork
  
networks:
  auctionnetwork:
    driver: bridge
    external: true
